name: Run mine_paper.py on Push

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      # This action checks out repository under $GITHUB_WORKSPACE
      uses: actions/checkout@v5

    - name: Set up Python
      # Installs the specified Python version
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 

    - name: Install python dependencies
      run: |
        pwd
        pip install uv
        uv venv
        source .venv/bin/activate

    - name: Run on aurora_2026/01/run2/
      # Executes your Python script
      run: uv run python mine_paper.py -d aurora_2026/01/run2/data

    - name: Run on aurora_2025/reframe_single_node_normalized/normal.smaller.log
      run: uv run python mine_paper.py -f aurora_2025/reframe_single_node_normalized/normal.smaller.log
